---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an S3 bucket and IAM user to be used with Veeam Capacity Tier. Object Lock is not enabled on the S3 bucket - Immutability Disabled.

Parameters:
  BucketName:
    Description: Bucket name. Bucket names must be globally unique.
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '[a-z0-9][a-z0-9\-]*'
    ConstraintDescription: Refer to AWS S3 documentation for name requirements and character limits. https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
  Username:
    Default: veeam-s3-user
    Description: IAM user name.
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9\-]*'
    ConstraintDescription: Refer to AWS IAM documentation for name requirements and character limits. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html
  OutputCredentialLocation:
    Default: "CloudFormation"
    Description: "Location to output the IAM user credentials. Options: CloudFormation, SecretsManager. Additional costs associated with SecretsManager"
    Type: String
    AllowedValues:
      - CloudFormation
      - SecretsManager

Conditions:
  UseSecretsManager: !Equals [!Ref OutputCredentialLocation, "SecretsManager"]

Resources:
  VeeamS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  IAMUser:
    Type: AWS::IAM::User
    DependsOn:
      - VeeamS3Bucket
    Properties:
      Path: /
      UserName: !Ref Username
      Policies:
        - PolicyName: veeam-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - s3:GetBucketObjectLockConfiguration
                  - s3:GetBucketVersioning
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${BucketName}/*"
                  - !Sub "arn:${AWS::Partition}:s3:::${BucketName}"
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                Resource: "*"

  IAMAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn:
      - IAMUser
    Properties:
      UserName: !Ref Username

  # Consider storing the IAM secret key in AWS Secrets Manager for secure storage and access.
  # This option is not enabled by default because secrets stored in AWS Secrets Manager incur a monthly cost. Refer to AWS documentation for details.
  # To enable it set the OutputCredentialLocation parameter to "SecretsManager".

  IAMSecretAccessKey:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Condition: UseSecretsManager
    Properties:
      Name: VeeamS3AccessKey
      Description: Access key used by Veeam to access S3.
      SecretString: !Sub '{"AccessKey":"${IAMAccessKey}","SecretAccessKey":"${IAMAccessKey.SecretAccessKey}"}'

Outputs:
  Region:
    Value: !Ref AWS::Region
    Description: AWS Region

  User:
    Value: !Ref IAMUser
    Description: Veeam S3 IAM user

  AccessKey:
    Value: !If
      - UseSecretsManager
      - !Sub "SecretKey stored in AWS Secrets Manager ${IAMSecretAccessKey}"
      - !Ref IAMAccessKey
    Description: Access key ID of new user

  SecretKey:
    Value: !If
      - UseSecretsManager
      - "SecretKey stored in AWS Secrets Manager"
      - !GetAtt IAMAccessKey.SecretAccessKey
    Description: Secret access key of new user

  VeeamS3Bucket:
    Value: !Ref VeeamS3Bucket
    Description: Veeam S3 bucket (object lock / immutability is not enabled)
